// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package recaptcha.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the reCAPTCHA module

	public static boolean aSU_reCAPTCHA(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (Boolean)Core.execute(context, "reCAPTCHA.ASU_reCAPTCHA", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static recaptcha.proxies.SecretKey gET_SecretKey(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "reCAPTCHA.GET_SecretKey", params);
			return result == null ? null : recaptcha.proxies.SecretKey.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static recaptcha.proxies.SiteKey gET_Sitekey(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "reCAPTCHA.GET_Sitekey", params);
			return result == null ? null : recaptcha.proxies.SiteKey.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean sUB_GoogleRecaptcha_Siteverify_V1(IContext context, String _responseToken, String _challenge)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ResponseToken", _responseToken);
			params.put("Challenge", _challenge);
			return (Boolean)Core.execute(context, "reCAPTCHA.SUB_GoogleRecaptcha_Siteverify_V1", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean sUB_GoogleRecaptcha_Siteverify_V2(IContext context, String _responseToken)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ResponseToken", _responseToken);
			return (Boolean)Core.execute(context, "reCAPTCHA.SUB_GoogleRecaptcha_Siteverify_V2", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}