// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package recaptcha.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This key is used to display the recaptcha widget on your site. By default the Google test key is used.
 */
public class SiteKey
{
	private final IMendixObject siteKeyMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "reCAPTCHA.SiteKey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		sitekey("sitekey");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public SiteKey(IContext context)
	{
		this(context, Core.instantiate(context, "reCAPTCHA.SiteKey"));
	}

	protected SiteKey(IContext context, IMendixObject siteKeyMendixObject)
	{
		if (siteKeyMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("reCAPTCHA.SiteKey", siteKeyMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a reCAPTCHA.SiteKey");

		this.siteKeyMendixObject = siteKeyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SiteKey.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static recaptcha.proxies.SiteKey initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return recaptcha.proxies.SiteKey.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static recaptcha.proxies.SiteKey initialize(IContext context, IMendixObject mendixObject)
	{
		return new recaptcha.proxies.SiteKey(context, mendixObject);
	}

	public static recaptcha.proxies.SiteKey load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return recaptcha.proxies.SiteKey.initialize(context, mendixObject);
	}

	public static java.util.List<recaptcha.proxies.SiteKey> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<recaptcha.proxies.SiteKey> result = new java.util.ArrayList<recaptcha.proxies.SiteKey>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//reCAPTCHA.SiteKey" + xpathConstraint))
			result.add(recaptcha.proxies.SiteKey.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of sitekey
	 */
	public final String getsitekey()
	{
		return getsitekey(getContext());
	}

	/**
	 * @param context
	 * @return value of sitekey
	 */
	public final String getsitekey(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.sitekey.toString());
	}

	/**
	 * Set value of sitekey
	 * @param sitekey
	 */
	public final void setsitekey(String sitekey)
	{
		setsitekey(getContext(), sitekey);
	}

	/**
	 * Set value of sitekey
	 * @param context
	 * @param sitekey
	 */
	public final void setsitekey(IContext context, String sitekey)
	{
		getMendixObject().setValue(context, MemberNames.sitekey.toString(), sitekey);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return siteKeyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final recaptcha.proxies.SiteKey that = (recaptcha.proxies.SiteKey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "reCAPTCHA.SiteKey";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
