// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package recaptcha.proxies;

/**
 * This key is used to display the recaptcha widget on your site. By default the Google test key is used.
 */
public class SiteKey
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject siteKeyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "reCAPTCHA.SiteKey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		sitekey("sitekey");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SiteKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "reCAPTCHA.SiteKey"));
	}

	protected SiteKey(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject siteKeyMendixObject)
	{
		if (siteKeyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("reCAPTCHA.SiteKey", siteKeyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a reCAPTCHA.SiteKey");

		this.siteKeyMendixObject = siteKeyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SiteKey.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static recaptcha.proxies.SiteKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return recaptcha.proxies.SiteKey.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static recaptcha.proxies.SiteKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new recaptcha.proxies.SiteKey(context, mendixObject);
	}

	public static recaptcha.proxies.SiteKey load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return recaptcha.proxies.SiteKey.initialize(context, mendixObject);
	}

	public static java.util.List<recaptcha.proxies.SiteKey> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<recaptcha.proxies.SiteKey> result = new java.util.ArrayList<recaptcha.proxies.SiteKey>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//reCAPTCHA.SiteKey" + xpathConstraint))
			result.add(recaptcha.proxies.SiteKey.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of sitekey
	 */
	public final java.lang.String getsitekey()
	{
		return getsitekey(getContext());
	}

	/**
	 * @param context
	 * @return value of sitekey
	 */
	public final java.lang.String getsitekey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sitekey.toString());
	}

	/**
	 * Set value of sitekey
	 * @param sitekey
	 */
	public final void setsitekey(java.lang.String sitekey)
	{
		setsitekey(getContext(), sitekey);
	}

	/**
	 * Set value of sitekey
	 * @param context
	 * @param sitekey
	 */
	public final void setsitekey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sitekey)
	{
		getMendixObject().setValue(context, MemberNames.sitekey.toString(), sitekey);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return siteKeyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final recaptcha.proxies.SiteKey that = (recaptcha.proxies.SiteKey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "reCAPTCHA.SiteKey";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
