// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package recaptcha.proxies;

public class SiteverifyRequest_V1
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject siteverifyRequest_V1MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "reCAPTCHA.SiteverifyRequest_V1";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		privatekey("privatekey"),
		remoteip("remoteip"),
		challenge("challenge"),
		response("response");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SiteverifyRequest_V1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "reCAPTCHA.SiteverifyRequest_V1"));
	}

	protected SiteverifyRequest_V1(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject siteverifyRequest_V1MendixObject)
	{
		if (siteverifyRequest_V1MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("reCAPTCHA.SiteverifyRequest_V1", siteverifyRequest_V1MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a reCAPTCHA.SiteverifyRequest_V1");

		this.siteverifyRequest_V1MendixObject = siteverifyRequest_V1MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SiteverifyRequest_V1.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static recaptcha.proxies.SiteverifyRequest_V1 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return recaptcha.proxies.SiteverifyRequest_V1.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static recaptcha.proxies.SiteverifyRequest_V1 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new recaptcha.proxies.SiteverifyRequest_V1(context, mendixObject);
	}

	public static recaptcha.proxies.SiteverifyRequest_V1 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return recaptcha.proxies.SiteverifyRequest_V1.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of privatekey
	 */
	public final java.lang.String getprivatekey()
	{
		return getprivatekey(getContext());
	}

	/**
	 * @param context
	 * @return value of privatekey
	 */
	public final java.lang.String getprivatekey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.privatekey.toString());
	}

	/**
	 * Set value of privatekey
	 * @param privatekey
	 */
	public final void setprivatekey(java.lang.String privatekey)
	{
		setprivatekey(getContext(), privatekey);
	}

	/**
	 * Set value of privatekey
	 * @param context
	 * @param privatekey
	 */
	public final void setprivatekey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String privatekey)
	{
		getMendixObject().setValue(context, MemberNames.privatekey.toString(), privatekey);
	}

	/**
	 * @return value of remoteip
	 */
	public final java.lang.String getremoteip()
	{
		return getremoteip(getContext());
	}

	/**
	 * @param context
	 * @return value of remoteip
	 */
	public final java.lang.String getremoteip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.remoteip.toString());
	}

	/**
	 * Set value of remoteip
	 * @param remoteip
	 */
	public final void setremoteip(java.lang.String remoteip)
	{
		setremoteip(getContext(), remoteip);
	}

	/**
	 * Set value of remoteip
	 * @param context
	 * @param remoteip
	 */
	public final void setremoteip(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String remoteip)
	{
		getMendixObject().setValue(context, MemberNames.remoteip.toString(), remoteip);
	}

	/**
	 * @return value of challenge
	 */
	public final java.lang.String getchallenge()
	{
		return getchallenge(getContext());
	}

	/**
	 * @param context
	 * @return value of challenge
	 */
	public final java.lang.String getchallenge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.challenge.toString());
	}

	/**
	 * Set value of challenge
	 * @param challenge
	 */
	public final void setchallenge(java.lang.String challenge)
	{
		setchallenge(getContext(), challenge);
	}

	/**
	 * Set value of challenge
	 * @param context
	 * @param challenge
	 */
	public final void setchallenge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String challenge)
	{
		getMendixObject().setValue(context, MemberNames.challenge.toString(), challenge);
	}

	/**
	 * @return value of response
	 */
	public final java.lang.String getresponse()
	{
		return getresponse(getContext());
	}

	/**
	 * @param context
	 * @return value of response
	 */
	public final java.lang.String getresponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.response.toString());
	}

	/**
	 * Set value of response
	 * @param response
	 */
	public final void setresponse(java.lang.String response)
	{
		setresponse(getContext(), response);
	}

	/**
	 * Set value of response
	 * @param context
	 * @param response
	 */
	public final void setresponse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String response)
	{
		getMendixObject().setValue(context, MemberNames.response.toString(), response);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return siteverifyRequest_V1MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final recaptcha.proxies.SiteverifyRequest_V1 that = (recaptcha.proxies.SiteverifyRequest_V1) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "reCAPTCHA.SiteverifyRequest_V1";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
