// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package recaptcha.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the reCAPTCHA module

	public static java.lang.String getLogNodeName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("reCAPTCHA.LogNodeName");
	}

	public static java.lang.String getSiteverifyURL_V2()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("reCAPTCHA.SiteverifyURL_V2");
	}
}